title: "Arman Mohammadi"
description: "Hydrology and Hydroclimatology — available Oct 2025"
url: "https://EzArmanim.github.io"
baseurl: "/Arman-Mohammadi"
repository: "EzArmanim/Arman-Mohammadi"

author:
  avatar: "profile.png"     # put this image in the repo root
  name: "Arman Mohammadi"
  bio: "MSc candidate; research in hydrology & hydroclimatology, long-term river-flow changes."
  location: "Turin, Italy"
  employer: "Politecnico di Torino"
  email: "arman.mohammadi@studenti.polito.it"
  github: "EzArmanim"
  linkedin: "arman-mohamadi"
  googlescholar: "https://scholar.google.co.uk/citations?hl=en&pli=1&user=bZie56oAAAAJ"

  orcid            : "https://orcid.org/0009-0003-8177-8884" # replace with your ORCID if you have one
  researchgate     : # add if you have
  scopus           : # add if you have

 # add/ensure these are present
minimal_mistakes_skin: default   # you can try "air", "contrast", or "dirt" if you want a lighter look
logo:                            # leave blank (no top-left logo)

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :  
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled" 
talkmap_link             : false      
comments:
  provider               : false

atom_feed:
  hide                   : false     

# SEO
social:
  type                   : Person
  name                   : "Arman Mohammadi"
  links:
    - "https://www.linkedin.com/in/arman-mohamadi"
    - "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
    - "https://github.com/EzArmanim"

# Analytics (disabled for now)
analytics:
  provider               : "false"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: certificates
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC 

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
